os: windows
language: bash

matrix:
  include:
    # - os: linux
    #   dist: trusty
    #   sudo: false
    #   language: dart
    #   dart:
    #     - stable
    #     - dev
    #   before_install:
    #     - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
    #     - evm install $EVM_EMACS --use --skip
    # env:
    #   - EVM_EMACS=emacs-24.4-travis
    #   - EVM_EMACS=emacs-24.5-travis
    #   - EVM_EMACS=emacs-25.1-travis
    #   - EVM_EMACS=emacs-25.2-travis
    #   - EVM_EMACS=emacs-25.3-travis
    #   - EVM_EMACS=emacs-26.1-travis
    #   - EVM_EMACS=emacs-git-snapshot-travis
    - os: windows
      language: bash
      before_install:
        - choco install dart-sdk
        - choco install emacs
        - choco install make
        - choco install python2
        - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
        - export "PATH=$PATH:$USERPROFILE\.cask\bin"

script:
  - make

notifications:
  email: false
