dist: trusty
sudo: false

os:
  - linux
  - windows

language: dart

dart:
  - stable
  - dev

matrix:
  include:
    - os: linux
    - os: windows
      language: generic
      before_install:
        - choco install dart

env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-git-snapshot-travis

before_install:

  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip

script:
  - make

notifications:
  email: false
